\copy ( SELECT n.id,n.scientific_name,cn.scientific_name, CASE n.type WHEN 0 THEN 'SCINAME' WHEN 1 THEN 'WELLFORMED' WHEN 2 THEN 'DOUBTFUL' WHEN 3 THEN 'BLACKLISTED' WHEN 4 THEN 'VIRUS' WHEN 5 THEN 'HYBRID' WHEN 6 THEN 'INFORMAL' WHEN 7 THEN 'CULTIVAR' WHEN 8 THEN 'CANDIDATUS' ELSE null END, p.monomial,p.subgenus,p.specific_epithet,p.infra_specific_epithet, CASE p.notho_type WHEN 0 THEN 'GENERIC' WHEN 1 THEN 'INFRAGENERIC' WHEN 2 THEN 'SPECIFIC' WHEN 3 THEN 'INFRASPECIFIC' ELSE null END, p.rank_marker,coalesce(p.authors_parsed,false),p.authorship,p.year,p.year_int,p.authorship_basionym,p.year_basionym,p.nom_status,n.modified FROM name_string n left join parsed_name p on n.id=p.name_fk left join name_string cn on n.canonical_name_fk=cn.id) to 'name.txt'

\copy ( SELECT id,citation FROM citation) to 'citation.txt'

\copy ( SELECT distinct on (u.id) u.id,c.resource_key,d.registry_key,u.name_fk,r.enum,u.parent_fk,u.is_synonym,u.pp_synonym_fk,ts.enum,'{'||ns.enum||'}',u.basionym_fk,u.kingdom_fk,u.phylum_fk,u.class_fk,u.order_fk,u.family_fk,u.genus_fk,u.subgenus_fk,u.species_fk,u.name_published_in_fk,u.according_to_fk,u.citation_fk, src.identifier as source_id, ir.identifier as "references", CASE u.origin WHEN 0 THEN 'SOURCE' WHEN 1 THEN 'DENORMED_CLASSIFICATION' WHEN 2 THEN 'VERBATIM_PARENT' WHEN 3 THEN 'VERBATIM_BASIONYM' WHEN 4 THEN 'PROPARTE' WHEN 5 THEN 'AUTONYM' WHEN 6 THEN 'IMPLICIT_NAME' WHEN 7 THEN 'MISSING_ACCEPTED' ELSE 'OTHER' END, u.lft,u.rgt,raw.remarks,u.modified FROM name_usage u JOIN checklist c on c.id=u.checklist_fk LEFT JOIN raw_usage raw ON raw.usage_fk=u.id LEFT JOIN term r2 ON r2.id=u.rank_fk LEFT JOIN term r ON r.id=r2.preferred_term_fk LEFT JOIN term ts2 ON ts2.id=u.tax_status_fk LEFT JOIN term ts ON ts.id=ts2.preferred_term_fk LEFT JOIN term ns2 ON ns2.id=u.nom_status_fk LEFT JOIN term ns ON ns.id=ns2.preferred_term_fk LEFT JOIN dataset d on d.id=u.dataset_fk LEFT JOIN identifier src ON src.usage_fk=u.id AND src.type_fk=2007 LEFT JOIN identifier ir ON ir.usage_fk=u.id AND ir.type_fk=2000) to 'name_usage.txt'

\copy ( SELECT u.id,c.resource_key, (u.rgt-u.lft)/2,u.num_children,u.num_synonyms,u.num_p,u.num_c,u.num_o,u.num_f,u.num_g,u.num_sg,u.num_s,u.num_is,u.modified FROM name_usage u JOIN checklist c on c.id=u.checklist_fk) to 'name_usage_metrics.txt'

\copy ( SELECT u.id,u.nub_fk,c.resource_key::uuid FROM name_usage u JOIN checklist c on c.id=u.checklist_fk WHERE u.nub_fk IS NOT NULL) to 'nub_rel.txt'

\copy ( SELECT c.resource_key,r.usage_fk,r.json,r.created FROM raw_usage r JOIN name_usage u ON u.id=r.usage_fk JOIN checklist c on c.id=u.checklist_fk WHERE r.json IS NOT NULL) to 'raw_usage.txt'

\copy ( SELECT c.resource_key, v.usage_fk,vn.vernacular_name,v.language,sex.enum,ls.enum,v.temporal,v.country,a.locality,a.location_id FROM vernacular_name v JOIN name_usage u ON u.id=v.usage_fk JOIN checklist c on c.id=u.checklist_fk JOIN vernacular_name_string vn ON v.name_string_fk=vn.id LEFT JOIN term sex2 ON sex2.id=v.sex_fk LEFT JOIN term sex ON sex.id=sex2.preferred_term_fk LEFT JOIN term ls2 ON ls2.id=v.life_stage_fk LEFT JOIN term ls ON ls.id=ls2.preferred_term_fk LEFT JOIN area a ON a.id=v.area_fk) to 'vernacular_name.txt'

\copy ( SELECT c.resource_key,usage_fk,d.description,dt.term,language,source_fk,creator,contributor,license FROM description d JOIN name_usage u ON u.id=d.usage_fk JOIN checklist c on c.id=u.checklist_fk LEFT JOIN term dt ON dt.id=d.type_fk) to 'description.txt'

\copy ( SELECT c.resource_key,usage_fk,marine,terrestrial,extinct,hybrid,living_period,age_in_days,size_in_millimeter,mass_in_gram,lf.term,hab.term FROM species_data d JOIN name_usage u ON u.id=d.usage_fk JOIN checklist c on c.id=u.checklist_fk LEFT JOIN term hab ON hab.id=d.habitat_fk LEFT JOIN term lf ON lf.id=d.life_form_fk) to 'species_info.txt'

\copy ( SELECT c.resource_key,usage_fk,s.citation_fk,dby.citation,scientific_name,r.enum,occurrence_id,institution_code,collection_code,catalog_number,locality,recorded_by,source_fk,verbatim_event_date,verbatim_label,verbatim_longitude,verbatim_latitude,null,t.enum FROM specimen s JOIN name_usage u ON u.id=s.usage_fk JOIN checklist c on c.id=u.checklist_fk LEFT JOIN citation dby ON dby.id=s.type_designated_by_fk LEFT JOIN term r2 ON r2.id=s.taxon_rank_fk LEFT JOIN term r ON r.id=r2.preferred_term_fk LEFT JOIN term t2 ON t2.id=s.type_status_fk LEFT JOIN term t ON t.id=t2.preferred_term_fk) to 'specimen.txt'

\copy ( SELECT distinct on (usage_fk,r.citation_fk) c.resource_key,usage_fk,r.citation_fk,r.type,r.remarks FROM name_usage_references r JOIN name_usage u ON u.id=r.usage_fk JOIN checklist c on c.id=u.checklist_fk) to 'literature.txt'

\copy ( SELECT c.resource_key,usage_fk,url,link,i.title,i.description,license,creator,created,publisher,rating FROM image i JOIN name_usage u ON u.id=i.usage_fk JOIN checklist c on c.id=u.checklist_fk) to 'image.txt'

\copy ( SELECT c.resource_key,usage_fk, CASE i.type_fk WHEN 2001 THEN 'LSID' WHEN 2002 THEN 'DOI' WHEN 2003 THEN 'HANDLER' WHEN 2004 THEN 'UUID' WHEN 2005 THEN 'FTP' WHEN 2006 THEN 'URI' ELSE 'UNKNOWN' END, identifier,i.title,subject FROM identifier i JOIN name_usage u ON u.id=i.usage_fk JOIN checklist c on c.id=u.checklist_fk WHERE i.type_fk != 2000 AND i.type_fk != 2007) to 'identifier.txt'

\copy ( SELECT c.resource_key,usage_fk,d.country,a.locality,a.location_id,os.enum,ts.enum,em.enum,ac.enum,d.start_day_of_year,d.end_day_of_year,d.start_year,d.end_year,d.source_fk,d.remarks FROM distribution d JOIN name_usage u ON u.id=d.usage_fk JOIN checklist c on c.id=u.checklist_fk LEFT JOIN area a ON a.id=d.area_fk LEFT JOIN term os2 ON os2.id=d.occurrence_status_fk LEFT JOIN term os ON os.id=os2.preferred_term_fk LEFT JOIN term ts2 ON ts2.id=d.threat_status_fk LEFT JOIN term ts ON ts.id=ts2.preferred_term_fk LEFT JOIN term em2 ON em2.id=d.establishment_means_fk LEFT JOIN term em ON em.id=em2.preferred_term_fk LEFT JOIN term ac2 ON ac2.id=d.appendix_cites_fk LEFT JOIN term ac ON ac.id=ac2.preferred_term_fk) to 'distribution.txt'
