checklistbank:
  db:
    dataSource:
      user: ${checklistbank.db.username}
      password: ${checklistbank.db.password}
      serverName: ${checklistbank.db.host}
      databaseName: ${checklistbank.db.name}
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    maximumPoolSize: '8'
    connectionTimeout: '10000'
  nub:
    indexDir: nubidx
    datasetKey: d7dddbf4-2cf0-4f39-9b2a-bb099caae36c