-- update rank type according to extended enum
-- https://github.com/gbif/gbif-api/commit/3826c67276b18dbaf1eae6b35e7334360bf3b9a5
DROP VIEW kname;
DROP VIEW nub;
DROP VIEW nub_homonyms;
DROP FUNCTION groupInfraspecificRanks(rank);

UPDATE name_usage set rank = 'UNRANKED' WHERE rank = 'INFORMAL';
UPDATE typification set rank = 'UNRANKED' WHERE rank = 'INFORMAL';
ALTER TABLE name_usage ALTER COLUMN rank type text;
ALTER TABLE typification ALTER COLUMN rank type text;

DROP TYPE rank;
CREATE TYPE rank AS ENUM ('DOMAIN', 'SUPERKINGDOM', 'KINGDOM', 'SUBKINGDOM', 'INFRAKINGDOM', 'SUPERPHYLUM', 'PHYLUM', 'SUBPHYLUM', 'INFRAPHYLUM', 'SUPERCLASS', 'CLASS', 'SUBCLASS', 'INFRACLASS', 'PARVCLASS', 'SUPERLEGION', 'LEGION', 'SUBLEGION', 'INFRALEGION', 'SUPERCOHORT', 'COHORT', 'SUBCOHORT', 'INFRACOHORT', 'MAGNORDER', 'SUPERORDER', 'GRANDORDER', 'ORDER', 'SUBORDER', 'INFRAORDER', 'PARVORDER', 'SUPERFAMILY', 'FAMILY', 'SUBFAMILY', 'INFRAFAMILY', 'SUPERTRIBE', 'TRIBE', 'SUBTRIBE', 'INFRATRIBE', 'SUPRAGENERIC_NAME', 'GENUS', 'SUBGENUS', 'INFRAGENUS', 'SECTION', 'SUBSECTION', 'SERIES', 'SUBSERIES', 'INFRAGENERIC_NAME', 'SPECIES_AGGREGATE', 'SPECIES', 'INFRASPECIFIC_NAME', 'GREX', 'SUBSPECIES', 'CULTIVAR_GROUP', 'CONVARIETY', 'INFRASUBSPECIFIC_NAME', 'PROLES', 'RACE', 'NATIO', 'ABERRATION', 'MORPH', 'VARIETY', 'SUBVARIETY', 'FORM', 'SUBFORM', 'PATHOVAR', 'BIOVAR', 'CHEMOVAR', 'MORPHOVAR', 'PHAGOVAR', 'SEROVAR', 'CHEMOFORM', 'FORMA_SPECIALIS', 'CULTIVAR', 'STRAIN', 'OTHER', 'UNRANKED');

ALTER TABLE name_usage ALTER COLUMN rank type rank USING (rank::rank);
ALTER TABLE typification ALTER COLUMN rank type rank USING (rank::rank);
