
ALTER TABLE ONLY media ADD CONSTRAINT media_usage_fk_fkey FOREIGN KEY (usage_fk) REFERENCES name_usage(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY media ADD CONSTRAINT media_source_fk_fkey FOREIGN KEY (source_fk) REFERENCES citation(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY typification ADD CONSTRAINT typification_usage_fk_fkey FOREIGN KEY (usage_fk) REFERENCES name_usage(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY typification ADD CONSTRAINT typification_source_fk_fkey FOREIGN KEY (source_fk) REFERENCES citation(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
