checklistbank:
  search:
    solr:
      serverType: @checklistbank.solr.type@
      collection: @checklistbank.solr.collection@
      serverHome: @checklistbank.solr.home@
  datasource:
    url: @checklistbank.db.url@
    username: @checklistbank.db.username@
    password: @checklistbank.db.password@
    data: classpath:init-db.sql
    hikari:
      idleTimeout: 60000
      maximumPoolSize: 10
      minimumIdle: 1
  ganglia:
    host: @ganglia.host@
    port: @ganglia.port@
gbif:
  portal:
    url: https://www.gbif-dev.org/
  api:
    url: https://api.gbif-dev.org/v1/
spring:
  main:
    allow-bean-definition-overriding: true
  #RabbitMQ
  rabbitmq:
    enabled: false
  # Liquibase
  liquibase:
    enabled: false
  #flyway
  flyway:
    enabled: false
